nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: [ '%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: [ 'GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE' ]
        allow_headers: [ 'Content-Type', 'Authorization', '*' ]
        allow_credentials: true
        expose_headers: []
        max_age: 0
        hosts: []
#        forced_allow_origin_value: ~
    paths:
        '^/api/':
            allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
            allow_headers: ['X-Custom-Auth', 'Content-Type', 'Authorization', 'Location']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTION']
            expose_headers: ['Link', 'Location']
            max_age: 3600
#        '^/':
#            origin_regex: true
#            allow_origin: [ '%env(CORS_ALLOW_ORIGIN)%' ]
#            allow_headers: ['X-Custom-Auth','Content-Type', 'Authorization']
#            allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTION']
#            expose_headers: ['Link', 'Location']
#            max_age: 3600
#            hosts: ['^api\.']