# Read the documentation: https://github.com/1up-lab/OneupFlysystemBundle/tree/master/Resources/doc/index.md
oneup_flysystem:
    adapters:
        public_uploads_adapter:
            local:
                directory: '%kernel.project_dir%/public_html/uploads'
    filesystems:
        public_uploads_filesystem:
            adapter: public_uploads_adapter
            mount: prublic_uploads_filesystem
