# Read the documentation: https://github.com/1up-lab/OneupFlysystemBundle/tree/master/Resources/doc/index.md
oneup_flysystem:
    adapters:
        public_uploads_adapter:
            local:
                directory: '%kernel.project_dir%/public_html/%uploads_dir_name%'
        private_uploads_adapter:
            local:
                directory: '%kernel.project_dir%/var/%uploads_dir_name%'
    filesystems:
        public_uploads_filesystem:
            adapter: public_uploads_adapter
            mount: public_uploads_filesystem
        private_uploads_filesystem:
            adapter: private_uploads_adapter
            mount: private_uploads_filesystem
