vich_uploader:
    db_driver: orm
    storage: flysystem

    mappings:
        media_object:
            uri_prefix: '%uploads_base_url%'
            upload_destination: public_uploads_filesystem
            # Will rename uploaded files using a uniqueid as a prefix.
            namer: Vich\UploaderBundle\Naming\OrignameNamer
        typeService:
            uri_prefix: '%uploads_base_url%/service_image'
            upload_destination: public_uploads_filesystem
            namer: Vich\UploaderBundle\Naming\OrignameNamer